### ISSUE TITLE
Как обрабатывать ошибки?

### ISSUE THREAD

**Issue by agran** [lentryd/NetSchoolApi#10]
Подскажите пожалуйста как обрабатывать ошибки.

Например у меня есть цикл и я делаю подряд много запросов `var result = await user.reportFile({`
Иногда на каком-то запросе происходит задержка, и вдруг скрипт прекращается выдав "DONE  Сеанс ЛОГИН успешно закрыт". Если запустить повторно, то может дойти до конца, а может снова вылететь в другом месте.

Как обработать неудачный запрос reportFile и сразу повторить с этого же места?

**Comment by lentryd** [comment]
try catch может помочь.
А вообще все функции в библиотеке это [промисы](https://learn.javascript.ru/promise#chto-takoe-promise) и у них ошибки ловятся с помощью `.catch`

В твоём случае можно сделать так.
``` js
const result = await user.reportFile({...}).catch(() => null);
if (result == null) console.log("Ошибка");
```

**Comment by lentryd** [comment]
> Иногда на каком-то запросе происходит задержка

Можешь в ручную увеличить время параметра timeout (см. документацию)

**Comment by lentryd** [comment]
> Как обработать неудачный запрос reportFile и сразу повторить с этого же места?

``` js
let result = null;

do {
  result = await user.reportFile({...}).catch(() => null);
} while (result == null);
```

только лучше еще добавить счетчик итераций, чтобы это не было бесконечно

**Comment by agran** [comment]
Не помогло, всё равно завершается с сообщением "DONE Сеанс ЛОГИН успешно закрыт".

**Comment by agran** [comment]
`			var result = null;
			var col = 0;
			do {
                console.log("reports/studenttotal/queue " + col);
				result = await user.reportFile({
					url: "reports/studenttotal/queue",
					filters: [
					  {
						filterId: "PCLID",
						filterValue: klassid, // ID класса
					  },
					  {
						filterId: "SEPTYPE",
						filterValue: "0", // ID класса
					  },
					  {
						filterId: "period",
						filterValue: period,
					  },
					],
				}).catch(() => null);
				col ++;
				if(col > 1){
					await new Promise(resolve => setTimeout(resolve, 1000));
				}
			} while (result == null && col < 25);`

**Comment by agran** [comment]
`
			var result = null;
			var col = 0;
			do {
                console.log("reports/studenttotal/queue " + col);
				result = await user.reportFile({
					url: "reports/studenttotal/queue",
					filters: [
					  {
						filterId: "PCLID",
						filterValue: klassid, // ID класса
					  },
					  {
						filterId: "SEPTYPE",
						filterValue: "0", // ID класса
					  },
					  {
						filterId: "period",
						filterValue: period,
					  },
					],
				}).catch(() => null);
				col ++;
				if(col > 1){
					await new Promise(resolve => setTimeout(resolve, 1000));
				}
			} while (result == null && col < 25);
`

**Comment by agran** [comment]
```
var result = null;
var col = 0;
do {
    console.log("reports/studenttotal/queue " + col);
    result = await user.reportFile({
        url: "reports/studenttotal/queue",
        filters: [{
                filterId: "PCLID",
                filterValue: klassid, // ID класса
            },
            {
                filterId: "SEPTYPE",
                filterValue: "0", // ID класса
            },
            {
                filterId: "period",
                filterValue: period,
            },
        ],
    }).catch(() => null);
    col++;
    if (col > 1) {
        await new Promise(resolve => setTimeout(resolve, 1000));
    }
} while (result == null && col < 25);
```

**Comment by lentryd** [comment]
Можешь ещё бахнуть try catch он 100% все отловить сможет, только тут уже нужно будет использовать рекурсию

**Comment by agran** [comment]
```
var result = null;
var col = 0;
do {
    console.log("reports/studenttotal/queue " + col);
    try {
        result = await user.reportFile({
            url: "reports/studenttotal/queue",
            filters: [{
                    filterId: "PCLID",
                    filterValue: klassid, // ID класса
                },
                {
                    filterId: "SEPTYPE",
                    filterValue: "0", // ID класса
                },
                {
                    filterId: "period",
                    filterValue: period,
                },
            ],
            timeout: 120000,
        }).catch(() => null);
    } catch (err) {
        console.log(JSON.stringify(err));
        result = null;
    }
    col++;
    if (col > 1) {
        await new Promise(resolve => setTimeout(resolve, 1000));
    }
} while (result == null && col < 25);
```
Посмотрю как этот код будет работать. Пока нормально.

**Comment by lentryd** [comment]
А скинь скриншот ошибки, которая приводила к завершению кода

**Comment by agran** [comment]
Пока не попадалась.

**Comment by agran** [comment]
```
var fail;
do {
try {
	var parents = await user
		.fetch("/webapi/userinfo/"+uchenikId+"/parents")
		.then((res) => res.json());

	fail = false;

} catch (err) {
	fail = true;
	console.log(inspect(err, { showHidden: true }));
	await new Promise(resolve => setTimeout(resolve, 10000));
} 
} while (fail);
```
Таким кодом делаю повторные запросы, так как сервер иногда возвращает 503 ошибку.

**Comment by agran** [comment]
Проблема в том что следующий код:
```
	try {
		result = await user.reportFile({
			url: "reports/studenttotal/queue",
			filters: [
					{
				filterId: "PCLID",
				filterValue: klassid, // ID класса
					},
					{
				filterId: "SEPTYPE",
				filterValue: "0",
					},
					{
				filterId: "period",
				filterValue: period,
					},
			],
			timeout: 5000
		});
	} catch (err) {
		console.log(inspect(err, { showHidden: true }));
		result = null;
	}
```
Не отлавливает ошибку, а скрипт просто без всяких сообщений прекращает работу.
