### ISSUE TITLE
Error: Fetch failed при логине

### ISSUE THREAD

**Issue by scffs** [lentryd/NetSchoolApi#11]
Базовый код из доки не работает

**Ожидаемое поведение**
Хотелось бы авторизироваться.
![image](https://github.com/lentryd/NetSchoolApi/assets/67464545/74d3b864-1181-4473-9510-129999c42340)

![image](https://github.com/lentryd/NetSchoolApi/assets/67464545/75bc562b-37a3-4c78-a191-3e96ca59c51e)

Версия последняя, нода v18.17.1

Если смотреть через burp, то роут для авторизации другой
![image](https://github.com/lentryd/NetSchoolApi/assets/67464545/7d860166-5b8d-4e2d-834a-1c115fb279a3)

**Comment by lentryd** [comment]
Привет
Возможно клиент сетевого обновили и старые методы авторизации не работают.

P.s. Хотел бы уточнить, это сетевой школы или техникума?

**Comment by lentryd** [comment]
Данный функционал, скорее всего, не будет реализован из-за слишком большого отличия от API, предназначенного для школ.
