### ISSUE TITLE
Как обрабатывать ошибки метода reportFile?

### ISSUE THREAD

**Issue by agran** [lentryd/NetSchoolApi#12]
Таким кодом делаю повторные запросы методом fetch, так как сервер иногда возвращает 503 ошибку:
```
const { inspect } = require('util');

var parents = null;
do {
  try {
	  parents = await user
		  .fetch("/webapi/userinfo/"+uchenikId+"/parents")
		  .then((res) => res.json());
  
  } catch (err) {
	  console.log(inspect(err, { showHidden: true }));
	  await new Promise(resolve => setTimeout(resolve, 10000));
  } 
} while (parents !== null);
```
Следующий код с методом reportFile не отлавливает ошибку, а скрипт просто без всяких сообщений прекращает работу с случае если сервер что-то не то ответил. 
```
try {
  result = await user.reportFile({
	url: "reports/studenttotal/queue",
	filters: [
			{
		filterId: "PCLID",
		filterValue: klassid, // ID класса
			},
			{
		filterId: "SEPTYPE",
		filterValue: "0",
			},
			{
		filterId: "period",
		filterValue: period,
			},
	],
	timeout: 5000
});
} catch (err) {
  console.log(inspect(err, { showHidden: true }));
  result = null;
}
```
В консоли только отображается  "DONE  Сеанс [МОЙ ЛОГИН] успешно закрыт" после чего весь мой скрипт прекращает работу.
Я попробовал посмотреть в результате чего происходит внештатное завершение.
Иногда сервер возвращает: 
`{"R":{"Success":false,"Message":"Ошибка запуска задачи"},"I":"0"}`
Но это не всё, бывает иногда и какая-то другая причина. В любом случае хотелось бы иметь возможность обработать ошибку, что бы сделать повторный запрос.

**Comment by lentryd** [comment]
Привет. Какая у тебя версия библиотеки?

**Comment by lentryd** [comment]
Вроде бы я понял в чем может быть проблема, попробуй версию [1.8.1](https://github.com/lentryd/NetSchoolApi/releases/tag/1.8.1)

**Comment by agran** [comment]
Как установить эту версию? У меня получается только через npm i netschoolapi 
Другие способы не работают

**Comment by lentryd** [comment]
```bash
npm i netschoolapi@1.8.1
```

Если не сработает, то попробуй:

1. Удалить текущую версию
```bash
npm un netschoolapi
```
2. Установить новую (указывать версию не нужно, автоматически устанавливается самая новая)
```bash
npm i netschoolapi
```

**Comment by agran** [comment]
сейчас ошибок не было, протестирую ещё когда будет повышенная нагрузка на сетевой город.

**Comment by lentryd** [comment]
Как я понимаю, все работает хорошо
