### ISSUE TITLE
status: 403

### ISSUE THREAD

**Issue by agran** [lentryd/NetSchoolApi#14]
```
node ocenTop.js
 INFO  Класс пользователя ИМЯ создан

Error: Fetch failed.
        - url: https://sgo.rso23.ru/webapi/schools/search
        - status: 403
    at Client.<anonymous> (/var/www/ocenki/data/node_modules/netschoolapi/dist/classes/Client/index.js:109:23)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/ocenki/data/node_modules/netschoolapi/dist/classes/Client/index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ERROR  Ошибка в коде привела к закрытию программы
Error: Не удалось получить список школ
    at /var/www/ocenki/data/node_modules/netschoolapi/dist/methods/logIn/methods/schoolInfo.js:23:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 DONE  Сеанс ИМЯ успешно закрыт
```
Выдаёт такое. Через браузер с этого IP и логина подключается.

**Comment by lentryd** [comment]
Привет!
Как производишь авторизацию в библиотеке? Значение `school` - число или название?

**Comment by agran** [comment]
Число.

**Comment by lentryd** [comment]
Да, там проблема с тем, что раньше можно было получить список всех школ по адресу `/webapi/schools/search`, а теперь разрабы системы решили запретит доступ к полному списку и теперь выводятся только по частичному совпадению названия `/webapi/schools/search?name=<название>`.

Пока для работы с либой можешь сделать некоторые изменения в коде:
1. В корне проекта найди файл `node_modules/netschoolapi/dist/methods/logIn/methods/schoolInfo.js`
2. Изменить ссылку `schools/search` на `schools/search?name=<название школы частично, можно даже одну букву>` (это примерно 16 строка кода)

Это вроде должно тебе помочь

**Comment by agran** [comment]
спасибо, помогло

**Comment by lentryd** [comment]
@agran можешь попробовать поменять `/webapi/schools/search?name=<название>` на `/webapi/schools/search?name=У`

**Comment by agran** [comment]
Что значит У?

**Comment by lentryd** [comment]
Просто русская буква у. Она встречается в большинстве названий школ. И хотелось бы понять будет ли работать такой способ

**Comment by agran** [comment]
Можно требовать задавать название школы в текстовом виде и в этом поиске использовать первую букву заданного названия.

**Comment by lentryd** [comment]
Ошибка исправлена в версии [1.8.2](https://github.com/lentryd/NetSchoolApi/releases/tag/1.8.2)
