### ISSUE TITLE
PCLID_IUP

### ISSUE THREAD

**Issue by dwap** [lentryd/NetSchoolApi#18]
**Описание проблемы**
При обращении к initfilters возвращается значение: 
```
{
    "filterId": "PCLID_IUP",
    "filterValue": "7_1",
    "filterText": "7 *"
}
```
Попробовал использовать метод .grades() выдаёт 409 ошибку.

**Ожидаемое поведение**
https://github.com/lentryd/NetSchoolApi/blob/b1b11525d56250d0d90693e5e32a0bf5641a8f7d/src/methods/grades.ts#L61
Использовать полное значение из initfilters. (есть ещё несколько мест где подставляется "_0"

**(пожалуйста, заполните следующую информацию):**
 - Среда: Windows
 - Версия NodeJS 20.10.0
 - Версия библиотеки 1.11.0

**Comment by lentryd** [comment]
Привет, очень интересно почему фильтр называется '7 *', это аккаунт ученика?

**Comment by dwap** [comment]
Нет, это родительский аккаунт. Если выбрать другого школьника, то будет что то вроде:
```
{
    "filterId": "PCLID_IUP",
    "filterValue": "646996_0",
    "filterText": "9в"
}
```

**Comment by lentryd** [comment]
Исправлено в версии [1.12.0](https://github.com/lentryd/NetSchoolApi/releases/tag/1.12.0)
