### ISSUE TITLE
Ошибка при входе с паролем на кириллице 

### ISSUE THREAD

**Issue by KOTOKOPOLb** [lentryd/NetSchoolApi#19]
**Описание проблемы**
Если в пароле пользователя есть кириллица (например русские буквы) - код не может зайти в систему

**Ожидаемое поведение**
Вход в аккаунт и получение данных?

**Шаги для воспроизведения**
1. Установить пароль с кириллицей (если он без)
2. Попытаться войти с помощью кода
3. Получить ошибку

**Логи**
```cs
 INFO  Класс пользователя Александр создан

(node:10980) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ERROR  Ошибка в коде привела к закрытию программы
Error: Не удалось войти. Проверьте введение данные.
    at D:\Visual Studio Project\VS Code\tests\node_modules\netschoolapi\dist\methods\logIn\methods\signIn.js:35:19
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
 DONE  Сеанс Александр успешно закрыт
 ```

**(пожалуйста, заполните следующую информацию):**
 - Среда: Windows 11, Debian 12
 - Версия NodeJS v22.11.0
 - Версия библиотеки 1.11.0

**Comment by KOTOKOPOLb** [comment]
Если входить через сайт и с помощью кода, 'lt' и хэш пароля отличаются
![image](https://github.com/user-attachments/assets/f1702dae-6d6d-498f-b85d-3c1a8d79f6b9)
![image](https://github.com/user-attachments/assets/d23e1b3d-ea0e-4cc5-997d-87cb21160479)
Если в коде самим указать хэш - тоже не помогает

**Comment by lentryd** [comment]
> Если входить через сайт и с помощью кода, 'lt' и хэш пароля отличаются

Да, так и должно быть, потому что твой пароль хэшируется и каждый раз разная соль приходит

**Comment by lentryd** [comment]
> Если в коде самим указать хэш - тоже не помогает

Возможность указать хэш пароля, нужна чтобы передать чистый md5 хэш пароля, без солей и других приколов.

Рассчитывалось, что для безопасности в альтернативных клиентах/ботах пароли в базе данных будут храниться не в чистом виде, а их md5 хэш

**Comment by lentryd** [comment]
> **Описание проблемы** Если в пароле пользователя есть кириллица (например русские буквы) - код не может зайти в систему

Попробуй в файле `node_modules/netschoolapi/dist/methods/logIn/methods/passwordHash.js` заменить 6 строку на
```js
return (0, crypto_1.createHash)("md5").update(str, "utf8").digest("hex");
```
Вроде как это должно решить проблему с кириллицей, но это не точно

**Comment by KOTOKOPOLb** [comment]
> Попробуй в файле `node_modules/netschoolapi/dist/methods/logIn/methods/passwordHash.js` заменить 6 строку на
> 
> ```js
> return (0, crypto_1.createHash)("md5").update(str, "utf8").digest("hex");
> ```
> 
> Вроде как это должно решить проблему с кириллицей, но это не точно

Это не дало результата, так как там уже прописана точно такая же строчка

**Comment by lentryd** [comment]
> Строчка обновилась сама, так как переустановил библиотеку, но результат такой же - ошибка входа

Можешь скинуть логи, какая ошибка выдаётся

**Comment by KOTOKOPOLb** [comment]
> Можешь скинуть логи, какая ошибка выдаётся

```cs
(node:16568) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Fetch failed.
        - url: https://sgo.tomedu.ru/webapi/login
        - status: 409
    at Client.<anonymous> (D:\Visual Studio Project\VS Code\tests\node_modules\@lentryd\web-client\dist\index.js:172:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Visual Studio Project\VS Code\tests\node_modules\@lentryd\web-client\dist\index.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
 ERROR  Ошибка в коде привела к закрытию программы
Error: Не удалось войти. Проверьте введение данные.
    at D:\Visual Studio Project\VS Code\tests\node_modules\netschoolapi\dist\methods\logIn\methods\signIn.js:36:19
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by lentryd** [comment]
Ты уверен что логин/пароль указан верно?

**Comment by KOTOKOPOLb** [comment]
да

**Comment by lentryd** [comment]
> да

Попробуй тогда заместо пароля передать md5 хеш

**Comment by KOTOKOPOLb** [comment]
> Как [здесь](https://github.com/lentryd/NetSchoolApi/blob/main/docs%2Fexamples%2FcontrolSession.md) в самом низу

знаю, результат такой же 
```cs
Error: Fetch failed.
        - url: https://sgo.tomedu.ru/webapi/login
        - status: 409
    at Client.<anonymous> (D:\Visual Studio Project\VS Code\tests\node_modules\@lentryd\web-client\dist\index.js:172:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Visual Studio Project\VS Code\tests\node_modules\@lentryd\web-client\dist\index.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
 ERROR  Ошибка в коде привела к закрытию программы
Error: Не удалось войти. Проверьте введение данные.
    at D:\Visual Studio Project\VS Code\tests\node_modules\netschoolapi\dist\methods\logIn\methods\signIn.js:36:19
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by KOTOKOPOLb** [comment]
В [библиотека на Python ](https://github.com/nm17/netschoolapi/) работает вход с кириллицей. Полазил, вроде бы там используется windows-1251, может поможет как-то эта информация

**Comment by KOTOKOPOLb** [comment]
уже попробовал, пока результат такой же (ошибка входа)

**Comment by KOTOKOPOLb** [comment]
всё так же

**Comment by KOTOKOPOLb** [comment]
Входит, проверил через свой аккаунт (где нет кириллицы в пароле) и всё работает

**Comment by lentryd** [comment]
Тогда не имею понятия почему такое происходит. Единственное что могу посоветовать это поменять пароль в настройках (на сетевом).

Если вдруг получится решить эту проблему, то пиши/предлагай пр

**Comment by KOTOKOPOLb** [comment]
@lentryd, Я смог исправить это! Добавив в `passwordHash.js` 2 новые строчки и изменив 1 старую я смог войти в аккаунт. Вот код который у меня получился:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = default_1;
const crypto_1 = require("crypto");
const iconv = require('iconv-lite');
function md5(str) {
    const buffer = iconv.encode(str, 'windows-1251');
    return (0, crypto_1.createHash)("md5").update(buffer).digest("hex");
}
function default_1(salt, password) {
    const hash = typeof password === "string" ? md5(password) : password.hash;
    const pw2 = md5(salt + hash);
    const pw = pw2.substring(0, password.length);
    return { pw, pw2 };
}
//# sourceMappingURL=passwordHash.js.map
```

**Comment by lentryd** [comment]
Добавил буфер в нужной кодировке и его отравил в хеш, верно?

**Comment by KOTOKOPOLb** [comment]
Ага, теперь и можно зайти как без кириллицы, так и с кириллицей

**Comment by lentryd** [comment]
Отлично, исправлено в версии [1.12.1](https://github.com/lentryd/NetSchoolApi/releases/tag/1.12.1)
