### ISSUE TITLE
Невозможно открыть сессию пользователя

### ISSUE THREAD

**Issue by reyzitwo** [lentryd/NetSchoolApi#7]
**Описание ошибки**
Как понимаю, не получается открыть сессию, поэтому код падает.
Код взят полностью из [README](https://github.com/lentryd/NetSchoolApi/blob/main/README.md#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B8), простое получение данных о пользователе.

**Скриншоты/Логи**

<img width="961" alt="Снимок экрана 2022-09-22 в 12 09 11" src="https://user-images.githubusercontent.com/73870113/191681786-c97facd1-01b1-4db5-8e76-ffc9952c6048.png">

**Информация о среде:**
 - Среда: локальный пк, macos
 - Версия NodeJS v16.15.1
 - Версия библиотеки ^1.7.1

**Comment by lentryd** [comment]
Привет. Правильно ли указаны данные пользователя?
Вообще такая ошибка появляется если неправильно указан логин/пароль/школа

**Comment by lentryd** [comment]
> Вообще такая ошибка появляется если неправильно указан логин/пароль/школа

Если логин и пароль указаны верно, то следует проверить правильность названия школы (желательно указывать ее полностью, либо указать ее id, который можно найти в коде элементов)

**Comment by reyzitwo** [comment]
@lentryd, привет, да, данные точно указаны корректно. Попробовал через id школы, также не пустило дальше.
На [аналогичном враппере для питона](https://github.com/nm17/netschoolapi) все работает

**Comment by lentryd** [comment]
@reyzitwo, можешь скинуть сайт своего сетевого. Возможно дело в нем. Так как в либе для питона делали какие-то адаптации для старых версий сетевого

**Comment by reyzitwo** [comment]
https://sgo.edu-74.ru/

**Comment by lentryd** [comment]
@reyzitwo, в версии [1.7.2](https://github.com/lentryd/NetSchoolApi/releases/tag/1.7.2) учел особенности твоего сетевого. Обнови библиотеку ( в рабочей папке введи `npm un netschoolapi`, а затем `npm un netschoolapi`).
Жду обратной связи касательно этой проблемы 😉

**Comment by reyzitwo** [comment]
Теперь все работает, спасибо)
