### ISSUE TITLE
Вывод Diary через .toJSON

### ISSUE THREAD

**Issue by alozoBack** [lentryd/NetSchoolApi#8]
В логе полученном через `.toJSON` в методе` Diary`

Запраишваю вывод в json он выводит 

> toJSON() {
>         return {
>             id: this.id,
>             subject: this.subject,
>             endDate: this._endDate,
>             startDate: this._startDate,
>             assignments: this.assignments.map((a) => a.toJSON()),
>         };
>     }

Если без `toJSON` то` Lesson {id: 7999784, subject: 'Алгебра', _endDate: '2022-10-25T11:15:00', _startDate: '2022-10-25T10:35:00', assignments: Array(1)}`

**Скриншоты/Логи**
![изображение](https://user-images.githubusercontent.com/108485035/197864038-739a4cdb-5f21-466f-b712-a4aa4ba9ca6f.png)
код: 

> const NS = require("netschoolapi").default;
> const user = new NS({
>   origin: "http://188.226.50.152/", // Origin вашего сайта
>   login: "", // Ваш логин
>   password: "", // Ваш пароль
>   school: "МБОУ Гимназия", // Название вашей школы (как на сайте)
> });
> 
> (async function () {
>   // Получаем дневник
>   const di = await user.diary();
>   console.log(di.days[0].lessons[3].toJSON)
> 
> 
>  await user.logOut();
> })();
> 
> 

 - Среда: VSC 
 - Версия NodeJS 18.2.0
 - OS Windows 11

Может конечно я идиот но фиг знает

**Comment by lentryd** [comment]
Смотри, `toJSON` это не параметр, а функция и ее надо вызывать (`Diary.toJSON()`). А вообще её можно не вызывать и использовать метод Node.js `JSON.stringify(Diary)`

[Вот тут](https://github.com/lentryd/NetSchoolApi/blob/main/docs/reference.md#diary) вся информация 😉
